Web/ServeIt.Web/Controllers/ReservationsController.cs
namespace ServeIt.Web.Controllers
{
    using System.Threading.Tasks;
    using AspNetCore.ReCaptcha;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Reservations;
    using ServeIt.Web.ViewModels.Reservations;

    [Authorize]
    public class ReservationsController : BaseController
    {
        private readonly IReservationsService reservationsService;

        public ReservationsController(IReservationsService reservationsService)
        {
            this.reservationsService = reservationsService;
        }

        [ValidateReCaptcha]
        [HttpPost]
        public async Task<IActionResult> MakeReservation(ReservationInputModel model)
        {
            var reservationId = await this.reservationsService.MakeReservation(model);

            return this.Redirect($"/Reservations/Reservation/{reservationId}");
        }

   
        public async Task<IActionResult> Reservation(string id)
        {
            var model = await this.reservationsService.TakeReservationInfo(id);
            return this.View(model);
        }

        public async Task<IActionResult> MyReservations(string id)
        {
            var model = await this.reservationsService.TakeAllMyReservation(id);
            return this.View(model);
        }
    }
}

Web/ServeIt.Web/Views/Reservations/MyReservations.cshtml
<br />
<br />
<br />


<section id="menu" class="menu section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>My</h2>
            <p>Reservations</p>
        </div>


        <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
            @foreach (var reservation in Model)
            {
                <div class="col-lg-6 menu-item">
                    <div class="menu-content">
                        <a asp-action="Reservation" asp-controller="Reservations" asp-route-id="@reservation.ReservationId">Reservation: @reservation.ReservationId</a><span>Date:@reservation.Date </span>
                    </div>
                    <div class="menu-ingredients">
                        Restaurant: @reservation.RestaurantName 
                    </div>
                </div>
            }




        </div>

    </div>
</section>

Web/ServeIt.Web/Views/Reservations/Reservation.cshtml
<br />
<br />
<br />


<section id="book-a-table" class="book-a-table">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Reservation: @Model.ReservationId</h2>
            <p>You have successfully made a reservation.</p>
            <p>We will contact with you for confirmation.</p>

        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">

                    <i class="bi bi-person"></i>
                    <h4>Full Name:</h4>
                    <p>@Model.FullName</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-envelope"></i>
                    <h4>Email:</h4>
                    <p>@Model.Email</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-phone"></i>
                    <h4>Phone Number:</h4>
                    <p>@Model.Phone</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-shop"></i>
                    <h4>Restaurant:</h4>
                    <p>@Model.RestaurantName</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-calendar-event"></i>
                    <h4>Date:</h4>
                    <p>@Model.Date</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-clock"></i>
                    <h4>Time:</h4>
                    <p>@Model.Time</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-people"></i>
                    <h4>People:</h4>
                    <p>@Model.People</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 form-group">
                <div class="info">   </div>
                <div class="phone">
                    <i class="bi bi-chat"></i>
                    <h4>Description:</h4>
                    <p>@Model.Description</p>
                </div>
            </div>

        </div>
        <div class="text-center">
            <a href="/" class="book-a-table-btn" style="width:auto;text-align:center">Home</a>
        </div>
    </div>
</section>