Web/ServeIt.Web/Controllers/CartController.cs
namespace ServeIt.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;
    using AspNetCore.ReCaptcha;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Orders;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.Orders;

    public class CartController : BaseController
    {
        private readonly ICartService cartService;

        public CartController(ICartService cartService, IUsersService usersService)
        {
            this.cartService = cartService;
        }

        [ValidateReCaptcha]
        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> AddToCart(string id,   AddToCartInputModel model)
        {
            if (model.Quantity > 0)
            {
                await this.cartService.AddToCart(id, this.UserId(), model);
            }

            return this.Redirect($"/Restaurants/Info/{model.RestaurantId}");
        }

        [Authorize(Roles = "User")]

        public async Task<IActionResult> Items(string id)
        {
            var model = await this.cartService.GetAllItemsForOrder(id);

            return this.View(model);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> RemoveItem(string id)
        {
            await this.cartService.RemoveItemFromCart(id);

            return this.Redirect($"/Cart/Items/{this.UserId()}");
        }

        private string UserId()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }
    }
}

Web/ServeIt.Web/Controllers/OrdersController.cs
namespace ServeIt.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Orders;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.Cart;

    [Authorize]

    public class OrdersController : BaseController
    {
        private readonly IOrdersService ordersService;
        private readonly IUsersService usersService;

        public OrdersController(
            IOrdersService ordersService,
            IUsersService usersService)
        {
            this.ordersService = ordersService;
            this.usersService = usersService;
        }

        public async Task<IActionResult> OrderedItems(string id)
        {
            var model = await this.ordersService.TakeAllItemsFromOrder(id);
            this.ViewData["OrderId"] = id;
            this.ViewData["IsItPayed"] = await this.ordersService.IsTheOrderPayed(id);
            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> DoneOrder(string id)
        {
            var restaurantId = await this.ordersService.DoneOrder(id);

            return this.Redirect($"/Restaurants/Edit/{restaurantId}");
        }

        public async Task<IActionResult> MyOrders(string id)
        {
            var model = await this.ordersService.TakeAllMyOrders(id);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RateOrder(string id, int rate)
        {
            await this.ordersService.RateOrder(id, rate);

            return this.Redirect($"/Orders/MyOrders/{this.UserId()}");
        }

        [HttpPost]
        public async Task<IActionResult> FinishOrder(string id, FinishOrderInputModel model)
        {
            if (string.IsNullOrEmpty(model.StreetName))
            {
                return this.Redirect("/Cart/ConfirmOrder");
            }

            await this.ordersService.FinishOrder(id, model);

            return this.Redirect($"/");
        }

        public async Task<IActionResult> ConfirmOrder(string id)
        {
            var user = await this.usersService.GetUser(this.UserId());

            var model = await this.ordersService.GetAllInfoAboutOrder(user);
            this.ViewData["UserId"] = this.UserId();

            return this.View(model);
        }

        private string UserId()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }
    }
}

Web/ServeIt.Web/Controllers/RestaurantsController.cs
namespace ServeIt.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Menus;
    using ServeIt.Services.Data.Orders;
    using ServeIt.Services.Data.Restaurants;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.Restaurants;

    public class RestaurantsController : BaseController
    {
        private readonly IRestaurantsService restaurantService;
        private readonly IMenusService menusService;
        private readonly IOrdersService ordersService;
        private readonly IUsersService usersService;

        public RestaurantsController(
            IRestaurantsService restaurantService,
            IMenusService menusService,
            IOrdersService ordersService,
            IUsersService usersService)
        {
            this.restaurantService = restaurantService;
            this.menusService = menusService;
            this.ordersService = ordersService;
            this.usersService = usersService;
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> Edit(string id)
        {
            var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!await this.restaurantService.AreYouTheOwner(id, ownerId))
            {
                return this.Redirect($"/Restaurants/Info/{id}");
            }

            var menuId = await this.menusService.RestaurantMenu(id);
            var menu = await this.menusService.TakeAllDishes(menuId);

            var restaurantInfo = await this.restaurantService.RestaurantInfo(id);
            var categories = await this.menusService.TakeAllCategoriesByMenu(menuId);
            var orders = await this.ordersService.TakeAllOrders(id);
            var model = new EditRestaurantViewModel
            {
                RestaurantId = id,
                Dishes = menu,
                MenuCategories = categories,
                RestaurantInfo = restaurantInfo,
                Orders = orders,
            };

            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> EditInfo(string id)
        {
            var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!await this.restaurantService.AreYouTheOwner(id, ownerId))
            {
                return this.Redirect($"/Restaurants/Info/{id}");
            }

            var info = await this.restaurantService.RestaurantInfo(id);
            var model = new AddRestaurantInputModel
            {
                Name = info.RestaurantName,
                About = info.About,
                CountryId = await this.restaurantService.TakeCountryId(info.Address.Split(", ")[0]),
                CityId = await this.restaurantService.TakeCityId(info.Address.Split(", ")[1]),
                Email = info.Email,
                Phone = info.PhoneNumber,
                StreetName = info.Address.Split(", ")[2],
            };
            await this.FillCountryAndCitiesSugestion();
            this.ViewData["RestaurantId"] = id;
            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]

        [HttpPost]
        public async Task<IActionResult> EditInfo(string id, AddRestaurantInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                await this.FillCountryAndCitiesSugestion();
                this.ViewData["RestaurantId"] = id;
                return this.View(model);
            }

            await this.restaurantService.EditRestaurantInfo(id, model);

            return this.Redirect($"/Restaurants/Edit/{id}");
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await this.restaurantService.GetAllRestaurants();

            return this.View(model);
        }

        [HttpGet("/Restaurants/All/{town}")]
        public async Task<IActionResult> All(string town)
        {
            var model = await this.restaurantService.GetAllRestaurants(town);
            if (model == null)
            {
                this.ViewData["town"] = town;
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FindRestaurant(string town)
        {

            if (string.IsNullOrEmpty(town))
            {
                return this.Redirect("/Restaurants/All");
            }

            return this.Redirect($"/Restaurants/All/{town}");
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> OwnedRestaurants(string id)
        {
            var model = await this.restaurantService.GetAllOwnedRestaurants(id);

            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> Add()
        {
             await this.FillCountryAndCitiesSugestion();

             return this.View();
        }

        [Authorize(Roles = "Restaurant")]
        [HttpPost]
        public async Task<IActionResult> Add(AddRestaurantInputModel model)
        {
             await this.FillCountryAndCitiesSugestion();

             if (!this.ModelState.IsValid)
            {
                return this.View(model);
           }

             var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

             await this.restaurantService.AddRestaurant(model, ownerId);

             return this.Redirect("/Restaurants/All");
        }

        public async Task<IActionResult> Info(string id)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await this.usersService.GetUser(userId);
            if (user == null)
            {
                return this.Redirect("/Users/Login");
            }

            var menuId = await this.menusService.RestaurantMenu(id);
            var menu = await this.menusService.TakeAllDishes(menuId);

            var restaurantInfo = await this.restaurantService.RestaurantInfo(id);
            var categories = await this.menusService.TakeAllCategoriesByMenu(menuId);

            var model = new EditRestaurantViewModel
            {
                RestaurantId = id,
                Dishes = menu,
                MenuCategories = categories,
                RestaurantInfo = restaurantInfo,
                UserFullName = user.FirstName + " " + user.LastName,
                UserPhone = user.PhoneNumber,
                UserEmail = user.Email,
                UserId = user.Id,
            };

            return this.View(model);
        }

        private async Task FillCountryAndCitiesSugestion()
        {
            var countries = await this.restaurantService.GetAllCountries();

            this.ViewData["Countries"] = countries;
        }
    }
}

Web/ServeIt.Web/Controllers/UsersController.cs
namespace ServeIt.Web.Controllers
{
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using AspNetCore.ReCaptcha;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authentication.Facebook;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.User;

    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        [Authorize]
        public async Task<IActionResult> Profile(string id)
        {
            var model = await this.usersService.GetUserInfo(id);

            return this.View(model);
        }

        [HttpPost]
        [Authorize]

        public async Task<IActionResult> EditUsername(EditProfileInputModel model)
        {
            if (model.Input.Length <= 20 &&
                model.Input.Length >= 3
                && !string.IsNullOrEmpty(model.Input))
            {
                await this.usersService.EditUsername(model, this.UserId());
            }

            return this.Redirect($"/Users/Profile/{this.UserId()}");
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> EditPhone(EditProfileInputModel model)
        {
            if (model.Input.Length <= 10 &&
                model.Input.Length >= 5 &&
                !string.IsNullOrEmpty(model.Input))
            {
                await this.usersService.EditPhoneNumber(model, this.UserId());
            }

            return this.Redirect($"/Users/Profile/{this.UserId()}");
        }

        [Authorize]
        [HttpPost]

        public async Task<IActionResult> EditEmail(EditProfileInputModel model)
        {
            var emailValidator = new EmailAddressAttribute();
            if (!string.IsNullOrEmpty(model.Input) && emailValidator.IsValid(model.Input))
            {
             await this.usersService.EditEmail(model, this.UserId());
            }

            return this.Redirect($"/Users/Profile/{this.UserId()}");
        }

        [Authorize]
        [HttpPost]

        public async Task<IActionResult> EditPassword(EditProfileInputModel model)
        {
            if (model.Input.Length <= 10 &&
                model.Input.Length >= 5 &&
                    model.Input == model.ReInput &&
                    !string.IsNullOrEmpty(model.Input) &&
                    !string.IsNullOrEmpty(model.ReInput))
            {
                await this.usersService.EditPassword(model, this.UserId());
            }

            await this.usersService.LogoutUser();
            return this.Redirect($"/Users/Login");
        }

        public async Task<IActionResult> Login()
        {
            return this.View();
        }

        [ValidateReCaptcha]
        [HttpPost]
        public async Task<IActionResult> Login(LoginUserInputModel model)
        {

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var user = await this.usersService.IsThereAnyUser(model);

            if (user == null )
            {
                this.ViewData["Error"] = "Invalid Username or Password";
                return this.View();
            }

            var res = await this.usersService.LoginUser(model);
            if (res)
            {
                return this.Redirect("/");
            }
            else
            {
                return this.View(model);
            }
        }

        public IActionResult Register()
        {
            return this.View();
        }

        [ValidateReCaptcha]
        [HttpPost]
        public async Task<IActionResult> Register(RegisterUserModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }
            if (await usersService.isUserWithEmail(model.Email))
            {
                this.ViewData["Error"] = "This email is already taken.";
                return this.View();
            }
            if (await usersService.isUserWithUsername(model.Username))
            {
                this.ViewData["Error"] = "This username is already taken.";
                return this.View();
            }

            await this.usersService.RegisterUser(model);

            return this.Redirect("/Users/Login");
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this.usersService.LogoutUser();
            return this.Redirect("/");
        }

        private string UserId()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }
    }
}

Web/ServeIt.Web/Views/Shared/_Layout.cshtml
@using ServeIt.Common
 @using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <!-- Favicons -->
    <link href="../assets/img/favicon.png" rel="icon">
    <link href="../assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->


    <link href="/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">





    <!-- Template Main CSS File -->
    <link href="/assets/css/style.css" rel="stylesheet">




    <!-- =======================================================
    * Template Name: Restaurantly - v3.3.0
    * Template URL: https://bootstrapmade.com/restaurantly-restaurant-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->


</head>
<body>


    <header id="header" class="fixed-top d-flex align-items-cente">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-lg-between">

            <h1 class="logo me-auto me-lg-0"><a asp-action="Index" asp-controller="Home">ServeIt</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0 ">

                <ul>
                    <li><a class="nav-link scrollto active" asp-action="Index" asp-controller="Home">Home <i class="bi bi-house-door"></i></a></li>
                    <li><a class="nav-link scrollto" href="/Restaurants/All">Restaurants <i class="bi bi-shop"></i></a></li>
                    @if (User.IsInRole("User"))
                    {
                        <li class="dropdown scrollto">
                            <a class="nav-link scrollto"><span>Profile</span> <i class="bi bi-chevron-down"></i></a>
                            <ul>


                                <li><a asp-controller="Orders" asp-action="MyOrders" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Orders</a></li>
                                <li><a asp-controller="Reservations" asp-action="MyReservations" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Reservations</a></li>
                                <li><a asp-controller="Users" asp-action="Profile" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Edit Profile</a></li>

                            </ul>
                        </li>
                        <li>
                            <a class="nav-link scrollto " asp-action="Items" asp-controller="Cart" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                                Cart<i class="bi bi-cart-check"></i>
                            </a>
                        </li>
                    }

                    @if (User.IsInRole("Restaurant"))
                    {
                        <li class="dropdown">
                            <a class="inactiveLink"><span>Restaurant Profile</span> <i class="bi bi-chevron-down"></i></a>
                            <ul>
                                <li><a asp-action="Add" asp-controller="Restaurants">Add Restaurant <i class="bi bi-patch-plus"></i></a></li>
                                <li>

                                    <a asp-controller="Restaurants" asp-action="OwnedRestaurants" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)"> My Restaurants</a>
                                </li>
                                <li><a asp-controller="Users" asp-action="Profile" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Profile <i class="bi bi-person-bounding-box"></i></a></li>


                            </ul>
                        </li>
                    }


                    @if (User.IsInRole("Administrator"))
                    {
                        <li><a asp-action="Users" asp-controller="Administration" asp-area="Administration">Users Controll</a></li>
                        <li><a asp-action="Restaurants" asp-controller="Administration" asp-area="Administration">Restaurants Controll</a></li>
                        <li><a asp-action="Destinations" asp-controller="Administration" asp-area="Administration">Add Destination</a></li>


                    }


                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->


            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-controller="Users" asp-action="Login" class="book-a-table-btn  d-lg-flex nav-link ">Login</a>
                <a asp-controller="Users" asp-action="Register" class="book-a-table-btn  d-lg-flex nav-link ">Register</a>
            }
            else
            {
                <a class="book-a-table-btn  d-lg-flex nav-link " href="/Users/Logout">Logout</a>

            }





        </div>
    </header>



    <partial name="_CookieConsentPartial" />
    <main role="main" id="main">
        @this.RenderBody()
    </main>





    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>


    <script src="/assets/vendor/aos/aos.js"></script>


    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <!-- Template Main JS File -->
    <script src="/js/main.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>

</body>
</html>