Web/ServeIt.Web/Controllers/CartController.cs
namespace ServeIt.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;
    using AspNetCore.ReCaptcha;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Orders;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.Orders;

    public class CartController : BaseController
    {
        private readonly ICartService cartService;

        public CartController(ICartService cartService, IUsersService usersService)
        {
            this.cartService = cartService;
        }

        [ValidateReCaptcha]
        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> AddToCart(string id,   AddToCartInputModel model)
        {
            if (model.Quantity > 0)
            {
                await this.cartService.AddToCart(id, this.UserId(), model);
            }

            return this.Redirect($"/Restaurants/Info/{model.RestaurantId}");
        }

        [Authorize(Roles = "User")]

        public async Task<IActionResult> Items(string id)
        {
            var model = await this.cartService.GetAllItemsForOrder(id);

            return this.View(model);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> RemoveItem(string id)
        {
            await this.cartService.RemoveItemFromCart(id);

            return this.Redirect($"/Cart/Items/{this.UserId()}");
        }

        private string UserId()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }
    }
}

Web/ServeIt.Web/Controllers/MenusController.cs
namespace ServeIt.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Menus;
    using ServeIt.Services.Data.Restaurants;
    using ServeIt.Web.ViewModels.Menu;

    [Authorize]

    public class MenusController : BaseController
    {
        private readonly IMenusService menusServices;

        public MenusController(IMenusService menusServices)
        {
            this.menusServices = menusServices;
        }

        public async Task<IActionResult> Add(string id)
        {
            var menuId = await this.menusServices.RestaurantMenu(id);

            if (menuId == null)
            {
                menuId = await this.menusServices.AddMenu(id);
            }

            this.ViewData["RestaurantId"] = id;
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(string id, AddDishInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewData["RestaurantId"] = id;
                return this.View(model);
            }

            var menuId = await this.menusServices.RestaurantMenu(id);

            await this.menusServices.AddDish(model, menuId);

            return this.Redirect($"/Restaurants/Edit/{id}");
        }

        public async Task<IActionResult> RemoveDish(string id)
        {
           var restaurantId = await this.menusServices.RemoveDish(id);

           this.ViewData["DishId"] = id;

           return this.Redirect($"/Restaurants/Edit/{restaurantId}");
        }

        public async Task<IActionResult> Edit(string id)
        {
            var model = await this.menusServices.TakeDish(id);

            this.ViewData["DishId"] = id;

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, AddDishInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewData["DishId"] = id;
                return this.View(model);
            }

            var restaurantId = await this.menusServices.EditDish(id, model);

            return this.Redirect($"/Restaurants/Edit/{restaurantId}");
        }
    }
}

Web/ServeIt.Web/Controllers/ReservationsController.cs
namespace ServeIt.Web.Controllers
{
    using System.Threading.Tasks;
    using AspNetCore.ReCaptcha;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Reservations;
    using ServeIt.Web.ViewModels.Reservations;

    [Authorize]
    public class ReservationsController : BaseController
    {
        private readonly IReservationsService reservationsService;

        public ReservationsController(IReservationsService reservationsService)
        {
            this.reservationsService = reservationsService;
        }

        [ValidateReCaptcha]
        [HttpPost]
        public async Task<IActionResult> MakeReservation(ReservationInputModel model)
        {
            var reservationId = await this.reservationsService.MakeReservation(model);

            return this.Redirect($"/Reservations/Reservation/{reservationId}");
        }

   
        public async Task<IActionResult> Reservation(string id)
        {
            var model = await this.reservationsService.TakeReservationInfo(id);
            return this.View(model);
        }

        public async Task<IActionResult> MyReservations(string id)
        {
            var model = await this.reservationsService.TakeAllMyReservation(id);
            return this.View(model);
        }
    }
}

Web/ServeIt.Web/Controllers/RestaurantsController.cs
namespace ServeIt.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ServeIt.Services.Data.Menus;
    using ServeIt.Services.Data.Orders;
    using ServeIt.Services.Data.Restaurants;
    using ServeIt.Services.Data.Users;
    using ServeIt.Web.ViewModels.Restaurants;

    public class RestaurantsController : BaseController
    {
        private readonly IRestaurantsService restaurantService;
        private readonly IMenusService menusService;
        private readonly IOrdersService ordersService;
        private readonly IUsersService usersService;

        public RestaurantsController(
            IRestaurantsService restaurantService,
            IMenusService menusService,
            IOrdersService ordersService,
            IUsersService usersService)
        {
            this.restaurantService = restaurantService;
            this.menusService = menusService;
            this.ordersService = ordersService;
            this.usersService = usersService;
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> Edit(string id)
        {
            var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!await this.restaurantService.AreYouTheOwner(id, ownerId))
            {
                return this.Redirect($"/Restaurants/Info/{id}");
            }

            var menuId = await this.menusService.RestaurantMenu(id);
            var menu = await this.menusService.TakeAllDishes(menuId);

            var restaurantInfo = await this.restaurantService.RestaurantInfo(id);
            var categories = await this.menusService.TakeAllCategoriesByMenu(menuId);
            var orders = await this.ordersService.TakeAllOrders(id);
            var model = new EditRestaurantViewModel
            {
                RestaurantId = id,
                Dishes = menu,
                MenuCategories = categories,
                RestaurantInfo = restaurantInfo,
                Orders = orders,
            };

            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> EditInfo(string id)
        {
            var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!await this.restaurantService.AreYouTheOwner(id, ownerId))
            {
                return this.Redirect($"/Restaurants/Info/{id}");
            }

            var info = await this.restaurantService.RestaurantInfo(id);
            var model = new AddRestaurantInputModel
            {
                Name = info.RestaurantName,
                About = info.About,
                CountryId = await this.restaurantService.TakeCountryId(info.Address.Split(", ")[0]),
                CityId = await this.restaurantService.TakeCityId(info.Address.Split(", ")[1]),
                Email = info.Email,
                Phone = info.PhoneNumber,
                StreetName = info.Address.Split(", ")[2],
            };
            await this.FillCountryAndCitiesSugestion();
            this.ViewData["RestaurantId"] = id;
            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]

        [HttpPost]
        public async Task<IActionResult> EditInfo(string id, AddRestaurantInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                await this.FillCountryAndCitiesSugestion();
                this.ViewData["RestaurantId"] = id;
                return this.View(model);
            }

            await this.restaurantService.EditRestaurantInfo(id, model);

            return this.Redirect($"/Restaurants/Edit/{id}");
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await this.restaurantService.GetAllRestaurants();

            return this.View(model);
        }

        [HttpGet("/Restaurants/All/{town}")]
        public async Task<IActionResult> All(string town)
        {
            var model = await this.restaurantService.GetAllRestaurants(town);
            if (model == null)
            {
                this.ViewData["town"] = town;
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FindRestaurant(string town)
        {

            if (string.IsNullOrEmpty(town))
            {
                return this.Redirect("/Restaurants/All");
            }

            return this.Redirect($"/Restaurants/All/{town}");
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> OwnedRestaurants(string id)
        {
            var model = await this.restaurantService.GetAllOwnedRestaurants(id);

            return this.View(model);
        }

        [Authorize(Roles = "Restaurant")]
        public async Task<IActionResult> Add()
        {
             await this.FillCountryAndCitiesSugestion();

             return this.View();
        }

        [Authorize(Roles = "Restaurant")]
        [HttpPost]
        public async Task<IActionResult> Add(AddRestaurantInputModel model)
        {
             await this.FillCountryAndCitiesSugestion();

             if (!this.ModelState.IsValid)
            {
                return this.View(model);
           }

             var ownerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

             await this.restaurantService.AddRestaurant(model, ownerId);

             return this.Redirect("/Restaurants/All");
        }

        public async Task<IActionResult> Info(string id)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await this.usersService.GetUser(userId);
            if (user == null)
            {
                return this.Redirect("/Users/Login");
            }

            var menuId = await this.menusService.RestaurantMenu(id);
            var menu = await this.menusService.TakeAllDishes(menuId);

            var restaurantInfo = await this.restaurantService.RestaurantInfo(id);
            var categories = await this.menusService.TakeAllCategoriesByMenu(menuId);

            var model = new EditRestaurantViewModel
            {
                RestaurantId = id,
                Dishes = menu,
                MenuCategories = categories,
                RestaurantInfo = restaurantInfo,
                UserFullName = user.FirstName + " " + user.LastName,
                UserPhone = user.PhoneNumber,
                UserEmail = user.Email,
                UserId = user.Id,
            };

            return this.View(model);
        }

        private async Task FillCountryAndCitiesSugestion()
        {
            var countries = await this.restaurantService.GetAllCountries();

            this.ViewData["Countries"] = countries;
        }
    }
}

Web/ServeIt.Web/Views/Restaurants/Add.cshtml
@model ServeIt.Web.ViewModels.Restaurants.AddRestaurantInputModel
@using ServeIt.Web.ViewModels.Restaurants
<br />
<br />
<br />
<br />

<section id="book-a-table" class="book-a-table d-flex align-items-center">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Add</h2>
            <p>Restaurant</p>
        </div>
        <form asp-action="Add" method="post" role="form" class="php-email-form" data-aos="fade-up" data-aos-delay="100">

            <div class="col-lg-4 col-md-6 form-group">
                <p class="text-danger"> @ViewData["Errors"]</p>
            </div>


            <div class="col">
                <div class="col-lg-4 col-md-6 form-group">
                    <input type="text" class="form-control" asp-for="Name" placeholder="Restaurant name..">
                    <span class="text-danger" asp-validation-for="Name">  </span>

                </div>

                <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
                    <select onchange="ChangeCities()" asp-for="CountryId" id="selectCountry" class="form-control" style="border-color: #625b4b; background: none; border-radius: 0; font-family: inherit; color:white">
                        <option value="" disabled selected hidden class="form-control" style="color:#625b4b">Choose Country</option>
                        @foreach (var country in (ViewData["Countries"]) as IEnumerable<CountriesViewModel>)
                        {
                            <option value="@country.CountryId" class="form-control" style="color:#625b4b">@country.CountryName</option>

                        }
                    </select>
                    <span asp-validation-for="CountryId" class="text-danger"></span>
                </div>

                <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
                    <select asp-for="CityId" id="selectCity" class="form-control" style="border-color: #625b4b; background: none; border-radius: 0; font-family: inherit; color:white">
                        <option value="" disabled selected hidden class="form-control" style="color:#625b4b">Choose City</option>
                        @foreach (var country in (ViewData["Countries"]) as IEnumerable<CountriesViewModel>)
                        {
                            @foreach (var city in country.Cities)
                            {
                                <option value="@city.CityId" class="form-control @country.CountryId" style="color:#625b4b">@city.CityName</option>

                            }

                        }
                    </select>
                    <span asp-validation-for="CityId" class="text-danger"></span>
                </div>

                <div class="col-lg-4 col-md-6 form-group">
                    <input type="text" asp-for="StreetName" class="form-control" placeholder="Street">
                    <span class="text-danger" asp-validation-for="StreetName">  </span>


                </div>
                <div class="col-lg-4 col-md-6 form-group">
                    <input type="text" asp-for="Phone" class="form-control" placeholder="Phone Number">
                    <span class="text-danger" asp-validation-for="Phone">  </span>


                </div>

                <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
                    <input type="email" class="form-control" asp-for="Email" placeholder="Email">
                    <span class="text-danger" asp-validation-for="Email"> </span>
                </div>



                <div class="col-lg-4 col-md-6 form-group mt-3 mt-md-0">
                    <label class="form-check-label">About </label>
                    <textarea class="form-control" asp-for="About" placeholder="About..."></textarea>
                    <span class="text-danger" asp-validation-for="About">  </span>

                </div>
           



                <div class="text-center"><button type="submit" onsubmit="UploadImage()">Add Restaurant</button></div>
            </div>
        </form>

    </div>
</section>


<script>
    function ChangeCities() {
        var x = document.getElementById("selectCountry").value;

        var options = document.getElementById("selectCity").getElementsByTagName("option");
        for (var i = 0; i < options.length; i++) {
            if (!options[i].classList.contains(x)) {
                options[i].style.display = "none";
            }
            else {
                options[i].style.display = "block";

            }
        }

    }
</script>

Web/ServeIt.Web/Views/Restaurants/All.cshtml
@using ServeIt.Web.ViewModels.Restaurants
<br />
<br />
<br />
<br />

<section id="why-us" class="why-us">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>All</h2>
            <p>Restaurants</p>


        </div>

        <br />
        @if (ViewData["town"] != null)
        {
            <div class="section-title">
                <p>Sorry, but we don't have restaurants in @ViewData["town"]</p>
            </div>
        }
        else
        {
            <div class="col-lg-4 col-md-6 form-group">
                <input type="text" onkeyup="myFunction()" name="town" class="form-control" id="search" placeholder="Search...">

            </div>
            <br />
            <div class="row">

                @foreach (var restaurant in Model as IEnumerable<AllRestaurantViewModel>)
                {

                    <div class="col-lg-4 mt-4 mt-lg-0" onclick="location.href = '/Restaurants/Info/@restaurant.RestaurantId'" style="cursor: pointer;">

                        <div class="box" data-aos="zoom-in" data-aos-delay="200">
                            <span>Rating: @restaurant.Rating.ToString("F2") / 5,00</span>
                            <h4>@restaurant.Name </h4>
                            <p id="address">Address: @restaurant.Country, @restaurant.City, @restaurant.Street.</p>
                        </div>
                        <br />
                    </div>

                }




            </div>
        }




    </div>
</section>

<script>
    function myFunction() {
        // Declare variables
        var input, filter,  i, txtValue;
        input = document.getElementById('search');
        filter = input.value.toUpperCase();
      
        restaurantsName = document.querySelectorAll("h4");



        for (var i = 0; i < restaurantsName.length; i++) {
            var address = restaurantsName[i].nextElementSibling.textContent.split("Address: ")[1];
            txtValue = restaurantsName[i].textContent + " " + address || restaurantsName[i].innerText + " " + address;
       
            var parrent = restaurantsName[i].parentElement.parentElement;
           
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                parrent.style.display = "block";
            }
            else {
                parrent.style.display = "none";
            }
        }

    
       

    }
</script>

Web/ServeIt.Web/Views/Restaurants/Edit.cshtml
@model ServeIt.Web.ViewModels.Restaurants.EditRestaurantViewModel


@using ServeIt.Web.ViewModels.Restaurants
<br />
<br />

<br />



<section id="specials" class="specials">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>Restaurant </h2>
            <p>Properties</p>
        </div>

        <div class="row" data-aos="fade-up" data-aos-delay="100">

            <div class="col-lg-3">
                <ul class="nav nav-tabs flex-column">
                    <li class="nav-item">
                        <a class="nav-link active show" data-bs-toggle="tab" href="#tab-1">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#tab-2">Reservations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#tab-3">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" href="#tab-4">Information</a>
                    </li>

                </ul>
            </div>

            <div class="col-lg-9 mt-4 mt-lg-0">
                <div class="tab-content">
                    <!-- ======= Orders Tab ======= -->

                    <div class="tab-pane active show" id="tab-1">
                        <div class="row">
                            <section id="menu" class="menu section-bg">
                                <div class="row" data-aos="fade-up" data-aos-delay="100">
                                    <div class="col-lg-12 d-flex justify-content-center">
                                        <ul id="menu-flters">
                                            <li data-filter="*" class="filter-active">All</li>
                                            <li data-filter=".filter-waiting">Waiting</li>
                                            <li data-filter=".filter-ready">Ready</li>
                                        </ul>
                                    </div>
                                </div>

                                <div id="orders" class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                                    @foreach (var order in Model.Orders)
                                    {

                                        <div class="col-lg-6 menu-item filter-@(order.IsItPayed?"ready":"waiting")">


                                            <div class="menu-content">

                                                <a href="/Orders/OrderedItems/@order.OrderId"> Order: @order.OrderId</a>
                                                <span>@order.Amount $</span>

                                            </div>
                                            <div class="menu-ingredients">

                                                <div class="menu-ingredients">
                                                    <p class="col-sm-8">Name: @order.FullName </p>
                                                    <p class="col-sm-8">Phone: @order.Phone </p>
                                                    <p class="col-sm-8">Street: @order.Street</p>
                                                    <p class="col-sm-8">Email: @order.Email<p>
                                                    <p class="col-sm-8">Date: @order.Date</p>
                                                    <p class="col-sm-8">Hour: @order.Hour</p>

                                                </div>

                                            </div>
                                        </div>

                                    }

                                </div>


                            </section>


                        </div>
                    </div>
                    <!-- ======= Menu Tab ======= -->

                    <div class="tab-pane " id="tab-3">


                        <section id="menu" class="menu section-bg">
                            <div class="row" data-aos="fade-up" data-aos-delay="100">
                                <div class="col-lg-12 d-flex justify-content-center">
                                    <a style="font-family:Playfair Display , serif;" asp-action="Add" asp-controller="Menus" asp-route-id="@Model.RestaurantId">Add Dish</a>
                                </div>                          
                             <br />  
                             <br />                            
                                 <div class="col-lg-12 d-flex justify-content-center">
                                        <ul id="menu-flters">
                                            <li data-filter="*" class="filter-active">All</li>
                                            @foreach (var category in Model.MenuCategories)
                                            {
                                                <li data-filter=".filter-@category">@category</li>
                                            }

                                        </ul>
                                    </div>
                            </div>

                            <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                                @foreach (var dish in Model.Dishes)
                                {
                                    <div class="col-lg-6 menu-item filter-@dish.CategoryName">
                                        <div class="menu-content">
                                            <a asp-action="Edit" asp-controller="Menus" asp-route-id=@dish.Id>@dish.Name</a>
                                            <span>$@dish.Price</span>
                                        </div>

                                        <div class="menu-ingredients">
                                            <p class="col-sm-8"> @dish.Ingredients</p>

                                        </div>
                                    </div>
                                }
                            </div>


                        </section>

                    </div>
                    <!-- ======= About Tab ======= -->

                    <div class="tab-pane " id="tab-4">
                        <div class="row">
                            <section id="contact" class="contact">
                                <div class="container" data-aos="fade-up">

                                    <div class="section-title">
                                        <h2>@Model.RestaurantInfo.RestaurantName</h2>
                                        <p>Contact Us</p>
                                    </div>
                                </div>


                                <div class="container" data-aos="fade-up">

                                    <div class="row mt-5">

                                        <div class="col-lg-4">
                                            <div class="info">
                                                <div class="address">
                                                    <i class="bi bi-geo-alt"></i>
                                                    <h4>Location:</h4>
                                                    <p>@Model.RestaurantInfo.Address</p>
                                                </div>

                                                <div class="open-hours">
                                                    <i class="bi bi-info"></i>
                                                    <h4>About us:</h4>
                                                    <p>
                                                        @Model.RestaurantInfo.About
                                                    </p>
                                                </div>

                                                <div class="email">
                                                    <i class="bi bi-envelope"></i>
                                                    <h4>Email:</h4>
                                                    <p>@Model.RestaurantInfo.Email</p>
                                                </div>

                                                <div class="phone">
                                                    <i class="bi bi-phone"></i>
                                                    <h4>Call:</h4>
                                                    <p>@Model.RestaurantInfo.PhoneNumber</p>
                                                </div>

                                            </div>

                                        </div>


                                    </div>

                                </div>
                                <div class="btns">
                                    <a asp-action="EditInfo" asp-controller="Restaurants" asp-route-id=@Model.RestaurantId class="btn-menu animated fadeInUp scrollto">Edit</a>
                                </div>
                            </section>



                        </div>
                    </div>

                </div>


              




            </div>

        </div>
     
    </div>

   

</section>

Web/ServeIt.Web/Views/Restaurants/OwnedRestaurants.cshtml
@using ServeIt.Web.ViewModels.Restaurants
<br />
<br />
<br />
<br />

<section id="why-us" class="why-us">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2>My</h2>
            <p>Restaurants</p>
        </div>

        <div class="row">



            @foreach (var restaurant in Model as IEnumerable<AllRestaurantViewModel>)
            {
            <div class="col-lg-4 mt-4 mt-lg-0" onclick="location.href = '/Restaurants/Edit/@restaurant.RestaurantId'" style="cursor: pointer;">

                <div class="box" data-aos="zoom-in" data-aos-delay="200">
                    <span>Rating: @restaurant.Rating.ToString("F2") / 5,00</span>
                    <h4>@restaurant.Name </h4>
                    <p>
                        Address: @restaurant.Country , @restaurant.City , @restaurant.Street.
                    </p>
                </div>
                <br />

            </div>
               

            }





        </div>

    </div>
</section>